# -*- coding: utf-8 -*-
"""WEEK_3_DISCUSSION_FORUM(HANDLING OF MISSING VALUES).ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1zPGjHb5f4oiL5SnecNoV1obqdVGO56Qn
"""

#Libraries
import pandas as pd
import numpy as np

#Create sample data
data = {'Feature1': [1.0, 2.0, None, 4.0],'Feature2': [None, 1.5, 3.5, 2.5]}

df = pd.DataFrame(data)

print(df)

#Display Missing values
print(df.isnull())

#Impute missing values with mean
from sklearn.impute import SimpleImputer
imputer = SimpleImputer(strategy='mean')
imputed_df_array = imputer.fit_transform(df)

# Convert the imputed array back to a DataFrame for better readability
imputed_df = pd.DataFrame(imputed_df_array, columns=df.columns)

# Display the imputed DataFrame
print(imputed_df)

#Load and prepare the California Housing dataset with artificially introduced missing values
from sklearn.datasets import fetch_california_housing

california = fetch_california_housing()

df = pd.DataFrame(data=california.data,columns=california.feature_names)

df['MedHouseVal'] = california.target  # Add the target variable

# Introduce random missing values for demonstration

np.random.seed(42)  # For reproducibility

mask = np.random.random(df.shape)

#Display mask results
print(mask)

df_with_missing = df.mask(mask < 0.1) # .mask replaces where the condition is True

# Load the dataset with missing values (Using the generated df directly)

data = df_with_missing.copy()


# Display the first few rows to examine the data structure

print("Dataset Preview:")

print(data.head())

print("\nDataset Info:")

print(data.info())

print("\nMissing Values by Column (Count):")

print(data.isnull().sum())

# Calculate and display missing values percentage by column

print("\nMissing Values by Column (Percentage):")

print((data.isnull().sum() / len(data)) * 100)

from matplotlib import pyplot as plt
import seaborn as sns

plt.figure(figsize=(8, 4))

sns.heatmap(data.isnull(), cbar=False, yticklabels=False, cmap='viridis')

plt.title('Missing Data Heatmap - California Housing', fontsize=16)

plt.xlabel('Features', fontsize=14)

plt.tight_layout()

plt.show()

# #added during screencast

# Bar chart showing count of missing values per column

plt.figure(figsize=(8, 6))
missing_values = pd.DataFrame(data.isnull().sum(), columns=['Missing Values Count'])
missing_values.sort_values('Missing Values Count', ascending=False, inplace=True)
missing_values.plot.bar()
plt.title('Missing Values Count by Column - California Housing', fontsize=16)
plt.ylabel('Count', fontsize=14)
plt.xlabel('Features', fontsize=14)
plt.tight_layout()
plt.show()

# #added during screencast
# Calculate percentage of missing values per column
missing_pct = data.isnull().mean() * 100
plt.figure(figsize=(8, 6))
missing_pct.sort_values(ascending=False).plot.bar()
plt.title('Percentage of Missing Values by Column', fontsize=16)
plt.ylabel('Percentage (%)', fontsize=14)
plt.xlabel('Features', fontsize=14)
plt.tight_layout()
plt.show()

features = ['MedInc', 'HouseAge', 'AveRooms']  # Median Income, House Age, Average Rooms

target = 'MedHouseVal'  # Median House Value in $100,000's

# Extract features and target

X = data[features]

y = data[target]

from sklearn.linear_model import LinearRegression
#create a model
model = LinearRegression()

# Attempt to fit the model with missing data

print("\nAttempting to fit model with missing data:")

try:

    model.fit(X, y)

    print("Model fitted successfully (unlikely with missing data)")

except ValueError as e:

    print(f"Error: {e}")

    print("As expected, scikit-learn cannot handle missing values directly")



# Display the number of rows with missing values

missing_rows = X.isnull().any(axis=1).sum()

total_rows = len(X)

print(f"\nRows with missing values: {missing_rows} out of {total_rows} ({missing_rows/total_rows*100:.1f}%)")

X_dropna = X[~X.isnull().any(axis=1) & ~y.isnull()]

y_dropna = y[~X.isnull().any(axis=1) & ~y.isnull()]  # Ensure target aligns with features

print(f"\nOriginal dataset shape: {X.shape}")

print(f"Dataset shape after dropping missing values: {X_dropna.shape}")

print(f"Data loss: {(1 - len(X_dropna)/len(X))*100:.2f}%")

# Now fit the model with the cleaned data

model.fit(X_dropna, y_dropna)

# Make predictions

predictions = model.predict(X_dropna)

print("\nPredictions:")

print(predictions)

plt.figure(figsize=(10, 6))
plt.scatter(y_dropna, predictions, alpha=0.6)
plt.plot([y_dropna.min(), y_dropna.max()], [y_dropna.min(), y_dropna.max()], 'k--', lw=2)
plt.xlabel('True House Values ($100,000s)', fontsize=14)
plt.ylabel('Predicted House Values ($100,000s)', fontsize=14)
plt.title('Prediction Accuracy with Dropped Missing Data - California Housing', fontsize=16)
plt.tight_layout()
plt.show()

from sklearn.metrics import mean_squared_error, r2_score
mse = mean_squared_error(y_dropna, predictions)
r2 = r2_score(y_dropna, predictions)

print(f"\nModel Performance:")
print(f"Mean Squared Error: {mse:.4f}")
print(f"R² Score: {r2:.4f}")

coef_df = pd.DataFrame({'Feature': features,'Coefficient': model.coef_})

print("\nModel Coefficients:")
print(coef_df)

plt.figure(figsize=(8, 5))
coef_df.plot(x='Feature', y='Coefficient', kind='bar', color='skyblue')
plt.title('Feature Importance - Impact on House Value', fontsize=16)
plt.ylabel('Coefficient', fontsize=14)
plt.xlabel('Feature', fontsize=14)
plt.xticks(rotation=45)
plt.tight_layout()
plt.show()

import ipywidgets as widgets
from IPython.display import display, HTML
#there are null values in the target variable, so we need to drop those rows
X = X[~y.isnull()]
y = y[~y.isnull()]
# Function to evaluate model performance

def evaluate_model(X_imputed, y_valid):

    model = LinearRegression()

    model.fit(X_imputed, y_valid)

    predictions = model.predict(X_imputed)

    mse = mean_squared_error(y_valid, predictions)

    r2 = r2_score(y_valid, predictions)

    return model, predictions, mse, r2
# Function to update outputs based on widget interaction

def update_output(method):

    plt.figure(figsize=(12, 8))
    # Create two subplots

    ax1 = plt.subplot(1, 2, 1)

    ax2 = plt.subplot(1, 2, 2)
    # Handle the selected imputation method

    if method == "Drop NA":

        # Remove rows with missing values

        X_clean = X[~X.isnull().any(axis=1) & ~y.isnull()]

        y_clean = y[~X.isnull().any(axis=1) & ~y.isnull()]

        model, predictions, mse, r2 = evaluate_model(X_clean, y_clean)

        method_desc = "Drops all rows with any missing values. Simple but can lead to significant data loss."
        # Show data loss in first plot

        data_loss = (1 - len(X_clean)/len(X)) * 100

        ax1.bar(['Original', 'After Dropping'], [len(X), len(X_clean)])

        ax1.set_title(f'Data Count\n(Lost {data_loss:.1f}% of data)')

        ax1.set_ylabel('Number of Records')

    elif method == "Mean":

        imputer = SimpleImputer(strategy='mean')

        X_imputed = pd.DataFrame(imputer.fit_transform(X), columns=X.columns)

        model, predictions, mse, r2 = evaluate_model(X_imputed, y)

        method_desc = "Replaces missing values with the mean of each column. Simple but can distort distributions."
        # Show before/after distribution

        for col in features:

            sns.kdeplot(X[col].dropna(), ax=ax1, label=f'Original {col}')

            sns.kdeplot(X_imputed[col], ax=ax1, linestyle='--', label=f'Imputed {col}')

        ax1.set_title('Distribution Before vs After Imputation')

        ax1.legend()
    elif method == "Median":

        imputer = SimpleImputer(strategy='median')

        X_imputed = pd.DataFrame(imputer.fit_transform(X), columns=X.columns)

        model, predictions, mse, r2 = evaluate_model(X_imputed, y)

        method_desc = "Replaces missing values with the median of each column. More robust to outliers than mean."
        # Show before/after distribution

        for col in features:

            sns.kdeplot(X[col].dropna(), ax=ax1, label=f'Original {col}')

            sns.kdeplot(X_imputed[col], ax=ax1, linestyle='--', label=f'Imputed {col}')

        ax1.set_title('Distribution Before vs After Imputation')

        ax1.legend()
    elif method == "KNN":

        imputer = KNNImputer(n_neighbors=5)

        X_imputed = pd.DataFrame(imputer.fit_transform(X), columns=X.columns)

        model, predictions, mse, r2 = evaluate_model(X_imputed, y)

        method_desc = "Uses K-nearest neighbors to estimate missing values. Preserves relationships but computationally intensive."
        # Show before/after distribution

        for col in features:

            sns.kdeplot(X[col].dropna(), ax=ax1, label=f'Original {col}')

            sns.kdeplot(X_imputed[col], ax=ax1, linestyle='--', label=f'Imputed {col}')

        ax1.set_title('Distribution Before vs After Imputation')

        ax1.legend()
    elif method == "MICE":

        imputer = IterativeImputer(random_state=42, max_iter=10)

        X_imputed = pd.DataFrame(imputer.fit_transform(X), columns=X.columns)

        model, predictions, mse, r2 = evaluate_model(X_imputed, y)

        method_desc = "Multiple Imputation by Chained Equations. Uses multiple variables to predict missing values. Sophisticated approach."

        # Show before/after distribution

        for col in features:

            sns.kdeplot(X[col].dropna(), ax=ax1, label=f'Original {col}')

            sns.kdeplot(X_imputed[col], ax=ax1, linestyle='--', label=f'Imputed {col}')

        ax1.set_title('Distribution Before vs After Imputation')

        ax1.legend()
    # Plot model predictions in second plot

    if method == "Drop NA":

        ax2.scatter(y_clean, predictions, alpha=0.5)

        ax2.plot([y_clean.min(), y_clean.max()], [y_clean.min(), y_clean.max()], 'k--')

        y_data = y_clean

    else:

        ax2.scatter(y, predictions, alpha=0.5)

        ax2.plot([y.min(), y.max()], [y.min(), y.max()], 'k--')

        y_data = y
    ax2.set_xlabel('Actual House Values')

    ax2.set_ylabel('Predicted House Values')

    ax2.set_title(f'Model Performance\nMSE: {mse:.2f}, R²: {r2:.2f}')
    plt.tight_layout()
    plt.show()

    # Display feature importance and method description

    if method != "Drop NA":

        coef_df = pd.DataFrame({'Feature': features, 'Coefficient': model.coef_})

        display(HTML(f"<h4>Feature Importance:</h4>"))

        display(coef_df)

    display(HTML(f"<h4>About {method} Imputation:</h4><p>{method_desc}</p>"))

# Create dropdown widget for imputation method selection

method_widget = widgets.Dropdown( options=['Drop NA', 'Mean', 'Median', 'KNN', 'MICE'],value='Mean', description='Method:', style={'description_width': 'initial'},layout={'width': '300px'})

# Display missing data information

print("Missing values in dataset:")

display(X.isna().sum())
# Create output widget and interactive function
output = widgets.Output()
out = widgets.interactive_output(update_output, {'method': method_widget})
# Display the interactive widget

display(HTML("<h2>Interactive Missing Data Solution Explorer - California Housing Dataset</h2>"))

display(HTML("<p>Select different methods to handle missing data and compare their impact on model performance.</p>"))

display(widgets.VBox([method_widget, out]))
# Add explanatory text

display(HTML("""

<div style="background-color: #f5f5f5; padding: 10px; border-radius: 5px; margin-top: 20px;">

<h3>How to Use This Explorer:</h3>

<ol>

    <li>Select an imputation method from the dropdown menu</li>

    <li>Observe how the data distribution changes in the left plot</li>

    <li>Compare model performance metrics and prediction accuracy in the right plot</li>

    <li>Review feature importance and method description below the plots</li>

</ol>

<p><strong>Note:</strong> The best imputation method often depends on your specific dataset and use case.</p>

</div>

"""))